server:
  port: 8080

spring:
  datasource:
    # 添加了 serverTimezone=Asia/Shanghai 防止时区报错
    url: jdbc:mysql://localhost:3306/user?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: ksthb15121530323
    driver-class-name: com.mysql.cj.jdbc.Driver
